---
stages:
  - lint
  - test

lint:
  stage: lint
  tags:
    - windows
    - hyperv
  script: vagrant validate

windows:
  stage: test
  tags:
    - windows
    - hyperv
  script:
    - vagrant up; vagrant destroy -f
...
