---
- hosts: all
  become: true
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (yum install -y python3)
      changed_when: false
  tasks:
    - include_role:
        name: gepardec.basics
    - include_role:
        name: geerlingguy.ntp
    - include_role:
        name: geerlingguy.docker
      vars: 
        docker_users:
          - vagrant
...
